stages:
  - build
  - deploy

build-job:     
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d
