stages:
  - build
  - deploy

build-job:     
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d
