image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
    - pwd && ls -AlF
  script:
    - docker compose -f docker-compose.ci.yml up -d
