stages:
  - build
  - lint
  - format
  - migrations
  - test
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker build -t booking-api-image .

lint-job:
  stage: lint
  script:
    - docker run -rm --network nginx-network booking-api-image ruff check

format-job:
  stage: format
  script:
    - docker run -rm --network nginx-network booking-api-image ruff format --check


migrations-job:
  stage: migrations
  script:
    - docker run -rm --network nginx-network booking-api-image alembic upgrade head


test-job:
  stage: test
  script:
    - docker run -rm --network nginx-network booking-api-image pytest -s -v

deploy-job:
  stage: deploy
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
  script:
    - docker compose -f docker-compose.ci.yml up -d
    #- docker exec nginx nginx -s reload
