stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t booking-api-image .

deploy-job:
  stage: deploy
  before_script:
    - cp ${ENV} .env
    - cp ${TEST_ENV} .env-test
    - pwd && ls -AlF
  script:
    - docker compose -f docker-compose.ci.yml up -d
