services:
  web-app:
    build:
      context: .
    container_name: web-app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./requirements.txt:/src/requirements.txt
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      #LANG: ru_RU.UTF-8
      #LC_ALL: ru_RU.UTF-8
    volumes:
      - pg_data_booking:/var/lib/postgresql/data
    ports:
      - "5432:${DB_PORT}"
    restart: unless-stopped

volumes:
  pg_data_booking:
    driver: local
