services:
  web-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: web-app-test
    env_file:
      - path: ./test.env
        required: true
    depends_on:
      - postgres
      - redis
    ports:
      - "8002:8002"
    volumes:
      - ./src:/src
      - ./tests:/src/tests
      - ./pytest.ini:/src/pytest.ini
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - path: ./test.env
        required: true
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data_booking:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - path: ./test.env
        required: true
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pg_data_booking:
    driver: local
