"""rooms: add unique fields

Revision ID: 422e406bbcee
Revises: 1ee9b8f0bc9d
Create Date: 2024-11-19 13:36:09.445046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "422e406bbcee"
down_revision: Union[str, None] = "1ee9b8f0bc9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_hotel_roomtitle_uc", "rooms", ["hotel_id", "title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_hotel_roomtitle_uc", "rooms", type_="unique")
    # ### end Alembic commands ###
