"""add unique fildes in Users

Revision ID: 1ee9b8f0bc9d
Revises: 45f7708c2661
Create Date: 2024-11-15 21:08:17.846425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ee9b8f0bc9d"
down_revision: Union[str, None] = "45f7708c2661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
