"""uniq location in hotels

Revision ID: bb3d93218134
Revises: 91ab22530416
Create Date: 2025-02-27 18:35:08.144735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb3d93218134"
down_revision: Union[str, None] = "91ab22530416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
