"""uniq title in faciliries

Revision ID: 65e56cdcac0b
Revises: bb3d93218134
Create Date: 2025-02-28 19:57:26.776652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65e56cdcac0b"
down_revision: Union[str, None] = "bb3d93218134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "facilities", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "facilities", type_="unique")
    # ### end Alembic commands ###
