"""name not uniq

Revision ID: 35c88a3cd7f1
Revises: 32ebb433211c
Create Date: 2025-02-27 15:59:45.501557

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "35c88a3cd7f1"
down_revision: Union[str, None] = "32ebb433211c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_name_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_name_key", "users", ["name"])
    # ### end Alembic commands ###
