"""uni1 name&title in hotels

Revision ID: 91ab22530416
Revises: 35c88a3cd7f1
Create Date: 2025-02-27 17:00:44.026261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91ab22530416"
down_revision: Union[str, None] = "35c88a3cd7f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uniq_title_location", "hotels", ["title", "location"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uniq_title_location", "hotels", type_="unique")
    # ### end Alembic commands ###
